apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-webapplication
  labels:
    app: springboot-webapplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-webapplication
  template:
    metadata:
      labels:
        app: springboot-webapplication
    spec:
      containers:
      - name: springboot-webapplication
        image: motoxplay/springboot-webapplication
        ports:
        - containerPort: 8080
